### ISSUE TITLE
Suggestion-Add custom portrait cameras

### ISSUE THREAD

**Issue by neistridlar** [gthaatar/UltimateShuttleIVA-FullRetro#10]
Only two of the kerbals have portrait cameras that show their entire face. Adding custom portrait cameras could help with this.

**Comment by gthaatar** [comment]
Noted. I believe it should be the first two seats no?  Because with those its actually the dash blocking them which will be easy to. Fix. 

If the 4 in back are messed ill need to do as you suggested too.

**Comment by neistridlar** [comment]
Two of the back seats have decent cameras. The rest are messed up one way or an other.

**Comment by gthaatar** [comment]
Roger, added to the project
