### ISSUE TITLE
Window Bugs

### ISSUE THREAD

**Issue by icetitan** [gthaatar/UltimateShuttleIVA-FullRetro#14]
![window2](https://user-images.githubusercontent.com/38858221/39488976-5201dfe8-4d84-11e8-997d-93abea65ed3b.png)
![window3](https://user-images.githubusercontent.com/38858221/39488989-5a589204-4d84-11e8-907e-6f27ec450db9.png)
also found a leak on the right side.
![screenshot 4](https://user-images.githubusercontent.com/38858221/39489003-65e476ec-4d84-11e8-8d32-6d4a823a8885.png)
Some Windows fall out ( look at the right side of the cockpit)

**Comment by gthaatar** [comment]
yep the windows are being, touchy. As stated in the PM i'm going to be messing with them to try and get them to behave.

However, with the issue in the first pic, that may or may not be fixed as that as far as I'm aware is actually the internal and external models not lining up just right. WHich is beyond my patience to mess with so yep.

**Comment by theonegalen** [comment]
There are stock cockpits with this issue as well.

**Comment by gthaatar** [comment]
Can confirm the windows are fixed, aside from the issue in the first picture, which is a model issue and not in my ballbark lol.
