### ISSUE TITLE
Off - Off Display

### ISSUE THREAD

**Issue by icetitan** [gthaatar/UltimateShuttleIVA-FullRetro#16]
![screenshot 9](https://user-images.githubusercontent.com/38858221/39636943-f55430e4-4fc1-11e8-95f0-830c3d4eb9d1.png)

**Comment by gthaatar** [comment]
Indeed, I did notice some...weirdness with this prop. I'm going to check its config to see what its actually supposed to do. I pulled it from the testbed IVA MoarDV uses for MAS and it was associated with the MechJeb controls.

**Comment by gthaatar** [comment]
Fixed. Will be in 0.05
