### ISSUE TITLE
Validation_Breaks?

### ISSUE THREAD

**Issue by debaker02** [gthaatar/UltimateShuttleIVA-FullRetro#4]
I could not find breaks to use to hold position on ground.

**Comment by gthaatar** [comment]
Brakes should be located on both Action Group control panels.  I know on the left side it may be obscurred by a precision control button thats not flush with the panel, but it should be present on the right.

Its also along the same level as the FDAI controls, so once the seats are pushed back it'll be easier to find it. 

Potentially I may reconfigure the panels slightly to create a specific Landing Control panel, combining brakes and gear with the chute controls.
