### ISSUE TITLE
All crew capable parts have crew capacity of 6

### ISSUE THREAD

**Issue by neistridlar** [gthaatar/UltimateShuttleIVA-FullRetro#7]
Title says it all really. I am testing on 1.3.1 right now, so that might be part of the issue.

**Comment by neistridlar** [comment]
I am guessing this is related, so posting it here, it seems All IVA's are now the shuttle IVA as well.

**Comment by gthaatar** [comment]
Yep. I uploaded a new MM patch. Haven't tested it yet but this may fix it.

**Comment by theonegalen** [comment]
Make sure you remove the space between @PART and [mk3cockpit_shuttle] if you still have the problem.

This is based on the config in the code section of this github.

**Comment by gthaatar** [comment]
Noted. Not sure why that wasn't part of what I uploaded earlier, but it is fixed now.
