### ISSUE TITLE
Suggestion_Rotate HUD

### ISSUE THREAD

**Issue by neistridlar** [gthaatar/UltimateShuttleIVA-FullRetro#8]
Currently the lower portion of the HUD appear to be horizontal. Because of this they block the lower part of the front window, without adding anything useful. Rotating the unit forward slightly should increase downward visibility, without compromising anything else. Looking at shuttle pictures it seems they are made this way as well.

**Comment by gthaatar** [comment]
Ah, good idea. Will do.
