### ISSUE TITLE
Window leak

### ISSUE THREAD

**Issue by icetitan** [gthaatar/UltimateShuttleIVA-FullRetro#9]
![window](https://user-images.githubusercontent.com/38858221/39428959-9867581a-4c89-11e8-81a9-ea72fc0c4854.png)
The window on the left side has a leak.

**Comment by gthaatar** [comment]
Noted, noticed this myself while setting up the new camera transforms. Im still playing with it, may have a fix in the next test release.

**Comment by gthaatar** [comment]
Should be fixed now in 0.03.
